### ISSUE TITLE
event "realtime:event" was not safe for net

### ISSUE THREAD

**Issue by iSentrie** [idan1432/fivem-realtime#2]
This is the error:

`event "realtime:event" was not safe for net`

Fix: #3 

Question: it synces time, but time goes 1 real life second = 1 game minute, so it means 1 game hour = 60s.
If `SetMillisecondsPerGameMinute(60000)`, clouds starts to struggle, any possible solution for this?

**Comment by EinfachMarcel** [comment]
To fix the `event "realtime:event" was not safe for net` you must change the `RegisterNetEvent("realtime:event")` in s-realtime.lua to `RegisterServerEvent("realtime:event")`

**Comment by iSentrie** [comment]
#3

**Comment by EinfachMarcel** [comment]
you only edited the c-realtime.lua but to fix it you must edit the s-realtime.lua

**Comment by EinfachMarcel** [comment]
Like this #4
